name: Build project

on:
  push:
    branches: [ master, feature, feature-a, feature-a1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: List files
      run: ls -la
      
    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
        
    - name: List files again
      run: ls -la

    - if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
      name: Install deps
      run: npm install

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Build project
      run: npm run build
